quartz:
  enabled: true
server:
  port: 9091
spring:
  application:
    name: Spring-Quartz-Scheduler                                       #Quartz\u8C03\u5EA6\u4E2D\u5FC3
  datasource:
    url: jdbc:mysql://localhost:3306/spring_quartz_job
    username: root
    password: 123
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false



